package initialize

import (
	"os"

	"smart-admin/server/global"
	"smart-admin/server/model/autocode"
	"smart-admin/server/model/example"
	"smart-admin/server/model/system"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// InitMysqlGorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func InitMysqlGorm() *gorm.DB {
	return GormMysql()
}

func InitPgsqlGorm() *gorm.DB {
	return GormPgSql()
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		system.SysDictionary{},
		system.SysOperationRecord{},
		system.SysAutoCodeHistory{},
		system.SysDictionaryDetail{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		system.SysAuthorityBtn{},
		// 示例模块表
		example.ExaFile{},
		example.ExaCustomer{},
		example.ExaFileChunk{},
		example.ExaFileUploadAndDownload{},

		// 自动化模块表
		// Code generated by smart-admin/server Begin; DO NOT EDIT.
		autocode.AutoCodeExample{},
		// Code generated by smart-admin/server End; DO NOT EDIT.
	)
	if err != nil {
		global.GVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GVA_LOG.Info("register table success")
}
